backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

local_backend: false

collections:
  - name: "site_settings"
    label: "Настройки сайта"
    files:
      - name: "general"
        label: "Основная информация"
        file: "index.html"
        fields:
          - label: "Заголовок страницы (Title)"
            name: "page_title"
            widget: "string"
            required: false
          - label: "Описание (Description)"
            name: "meta_description"
            widget: "text"
            required: false
